### ISSUE TITLE
Icons in the eww Memories dot files are turned into boxes with symbols in them

### ISSUE THREAD

**Issue by Sininenblue** [mehedirm6244/My_XFCE_dotties#6]
I was trying to use the the eww widget from the Memories section and I found that all the icons, including the one in the weather script, were turned into boxes
https://imgur.com/HAg2cwks.png
I'm guessing it's a font issue, but I'm not exactly sure how to fix that.

**Comment by mehedirm6244** [comment]
I'm extremely sorry, I forgot to add the font stuffs inside the repo 😥 Let me add the fonts first

**Comment by mehedirm6244** [comment]
### Updated repo!
- Copy `memories/local/share/fonts/feather.ttf` to `~/.local/share/fonts/`
- If you go through the scss of the eww weather widget....
```
.weathicon
{
	font-family: "JetBrainsMono Nerd Font";
	margin: 0 25 0 35;
	font-size: 38;
	color: $accent;
}
```
you'll see that I'm using "JetBrainsMono **Nerd** Font" for the weather symbol. Install JetBrainsMono Nerd font (it's already available in AUR, if you use Arch/derivative btw). However, any nerd patched font should work, just put your desired font name at the place of "JetBrainsMono Nerd Font".
@Sininenblue

**Comment by Sininenblue** [comment]
Thanks! It's fully working now
